
import React from 'react';
import {
  Home,
  UserPlus,
  Hospital,
  Stethoscope,
  Activity,
  Ambulance,
  FileText,
  Scissors,
  ShieldCheck,
  Heart,
  Syringe,
  AlertCircle,
  CheckSquare
} from 'lucide-react';
import { MedicationCategory } from './types';

export const SECTORS = [
  'Clínica Médica',
  'Clínica Cirúrgica',
  'Obstetrícia',
  'Pediatria',
  'Sala Vermelha',
  'Pronto Socorro',
  'Ambulatório',
  'UTI Adulto',
  'UTI Neonatal',
  'Centro Cirúrgico'
];

export const DURATION_OPTIONS = ['C.C', '1', '2', '3', '5', '7', '10', '14', '21'];
export const FREQUENCY_OPTIONS = ['24/24', '12/12', '08/08', '06/06', '04/04', '48/48', 'Dose Única'];

export const DDD_MAP: Record<string, number> = {
  "ACICLOVIR COMP 200MG": 3.0,
  "ACICLOVIR PO P/ SOL INJ 250MG": 3.0,
  "AMICACINA SOL INJ 250MG/ML 2ML": 1.0,
  "AMOXICILINA + ACIDO CLAVULANICO COMP 500 + 125MG": 1.0,
  "AMOXICILINA + ACIDO CLAVULANICO PO P/ SOL INJ 1G + 200MG": 1.0,
  "AMOXICILINA + CLAVULANATO DE POTASSIO COMP 875 + 125MG": 1.0,
  "AMOXICILINA + CLAVULANATO SUSP ORAL 250 + 62,5MG/5ML 75ML": 1.0,
  "AMPICILINA + SULBACTAM PO P/ SOL INJ 1 + 0,5G": 2.0,
  "AMPICILINA SODICA PO P/ SOL INJ 1G": 2.0,
  "ANFOTERICINA B DESOXICOLATO PO P/ SOL INJ 50MG": 0.04,
  "AZITROMICINA COMP 500MG": 0.5,
  "BENZILPENICIL BENZATINA PO P/ SOL INJ 1.200.000UI": 1.0,
  "BENZILPENICILINA POTASS PO P/ SOL INJ 5.000.000UI": 3.6,
  "CEFALEXINA COMP 500MG": 2.0,
  "CEFALOTINA PO P/ SOL INJ 1G": 2.0,
  "CEFAZOLINA PO P/ SOL INJ 1G": 3.0,
  "CEFEPIME PO P/ SOL INJ 1G": 2.0,
  "CEFOXITINA PO P/ SOL INJ 1000MG": 6.0,
  "CEFTAZIDIMA + AVIBACTAM PO P/ SOL INJ 2,5G": 1.0,
  "CEFTAZIDIMA PO P/ SOL INJ 1G": 4.0,
  "CEFTRIAXONA PO P/ SOL INJ 1G": 2.0,
  "CEFTRIAXONA PO P/ SOL INJ IM 1G": 2.0,
  "CEFUROXIMA PO P/ SOL INJ 750MG": 3.0,
  "CIPROFLOXACINO COMP 500MG": 1.0,
  "CIPROFLOXACINO SOL INJ 2MG/ML 200ML": 0.8,
  "CLARITROMICINA PO P/ SOL INJ 500MG": 1.0,
  "CLINDAMICINA SOL INJ 150MG/ML 4ML": 1.8,
  "FLUCONAZOL CAPS 150MG": 0.2,
  "FLUCONAZOL SOL INJ 2MG/ML 100ML": 0.2,
  "GENTAMICINA SOL INJ 40MG/ML": 0.24,
  "IVERMECTINA COMP 6MG": 1.0,
  "LEVOFLOXACINO SOL INJ 5MG/ML 100ML": 0.5,
  "LINEZOLIDA SOL INJ 2MG/ML 300ML": 1.2,
  "MEROPENEM PO P/ SOL INJ 1G": 2.0,
  "METRONIDAZOL COMP 250MG": 1.5,
  "METRONIDAZOL SOL INJ 5MG/ML 100ML": 1.5,
  "MUPIROCINA 2% CREME 20MG/G 15G": 1.0,
  "NISTATINA SUSP ORAL 100.000UI/ML 50ML": 1.0,
  "OSELTAMIVIR FOSFATO CAPS 30MG": 0.15,
  "OSELTAMIVIR FOSFATO CAPS 45MG": 0.15,
  "OSELTAMIVIR FOSFATO CAPS 75MG": 0.15,
  "OXACILINA PO P/ SOL INJ 500MG": 2.0,
  "PIPERACILINA + TAZOBACTAM PO P/ SOL INJ 4 + 0,5G": 14.0,
  "POLIMIXINA B PO P/ SOL INJ 500.000UI": 0.15,
  "SULFAMETOXAZOL + TRIMETOPRIMA COMP 400 + 80MG": 1.92,
  "SULFAMETOXAZOL + TRIMETOPRIMA SOL INJ 80 + 16MG/ML 5ML": 1.92,
  "TEICOPLANINA PO P/ SOL INJ 400MG": 0.4,
  "VANCOMICINA PO P/ SOL INJ 500MG": 2.0
};

export const MEDICATION_LISTS: Record<MedicationCategory, string[]> = {
  [MedicationCategory.ANTIMICROBIANO]: [
    "ACICLOVIR COMP 200MG",
    "ACICLOVIR PO P/ SOL INJ 250MG",
    "AMICACINA SOL INJ 250MG/ML 2ML",
    "AMOXICILINA + ACIDO CLAVULANICO COMP 500 + 125MG",
    "AMOXICILINA + ACIDO CLAVULANICO PO P/ SOL INJ 1G + 200MG",
    "AMOXICILINA + CLAVULANATO DE POTASSIO COMP 875 + 125MG",
    "AMOXICILINA + CLAVULANATO SUSP ORAL 250 + 62,5MG/5ML 75ML",
    "AMPICILINA + SULBACTAM PO P/ SOL INJ 1 + 0,5G",
    "AMPICILINA SODICA PO P/ SOL INJ 1G",
    "ANFOTERICINA B DESOXICOLATO PO P/ SOL INJ 50MG",
    "AZITROMICINA COMP 500MG",
    "BENZILPENICIL BENZATINA PO P/ SOL INJ 1.200.000UI",
    "BENZILPENICILINA POTASS PO P/ SOL INJ 5.000.000UI",
    "CEFALEXINA COMP 500MG",
    "CEFALOTINA PO P/ SOL INJ 1G",
    "CEFAZOLINA PO P/ SOL INJ 1G",
    "CEFEPIME PO P/ SOL INJ 1G",
    "CEFOXITINA PO P/ SOL INJ 1000MG",
    "CEFTAZIDIMA + AVIBACTAM PO P/ SOL INJ 2,5G",
    "CEFTAZIDIMA PO P/ SOL INJ 1G",
    "CEFTRIAXONA PO P/ SOL INJ 1G",
    "CEFTRIAXONA PO P/ SOL INJ IM 1G",
    "CEFUROXIMA PO P/ SOL INJ 750MG",
    "CIPROFLOXACINO COMP 500MG",
    "CIPROFLOXACINO SOL INJ 2MG/ML 200ML",
    "CLARITROMICINA PO P/ SOL INJ 500MG",
    "CLINDAMICINA SOL INJ 150MG/ML 4ML",
    "FLUCONAZOL CAPS 150MG",
    "FLUCONAZOL SOL INJ 2MG/ML 100ML",
    "GENTAMICINA SOL INJ 40MG/ML",
    "IVERMECTINA COMP 6MG",
    "LEVOFLOXACINO SOL INJ 5MG/ML 100ML",
    "LINEZOLIDA SOL INJ 2MG/ML 300ML",
    "MEROPENEM PO P/ SOL INJ 1G",
    "METRONIDAZOL COMP 250MG",
    "METRONIDAZOL SOL INJ 5MG/ML 100ML",
    "MUPIROCINA 2% CREME 20MG/G 15G",
    "NISTATINA SUSP ORAL 100.000UI/ML 50ML",
    "OSELTAMIVIR FOSFATO CAPS 30MG",
    "OSELTAMIVIR FOSFATO CAPS 45MG",
    "OSELTAMIVIR FOSFATO CAPS 75MG",
    "OXACILINA PO P/ SOL INJ 500MG",
    "PIPERACILINA + TAZOBACTAM PO P/ SOL INJ 4 + 0,5G",
    "POLIMIXINA B PO P/ SOL INJ 500.000UI",
    "SULFAMETOXAZOL + TRIMETOPRIMA COMP 400 + 80MG",
    "SULFAMETOXAZOL + TRIMETOPRIMA SOL INJ 80 + 16MG/ML 5ML",
    "TEICOPLANINA PO P/ SOL INJ 400MG",
    "VANCOMICINA PO P/ SOL INJ 500MG"
  ],
  [MedicationCategory.ANTIFUNGICO]: [],
  [MedicationCategory.ANTIVIRAL]: [],
  [MedicationCategory.PSICOTROPICO]: [],
  [MedicationCategory.BIOLOGICO]: []
};

export const ANTIBIOTICS_LIST = Object.keys(DDD_MAP);

export const MENU_ITEMS = [
  { id: 'inicio', label: 'Início', icon: <Home size={20} />, color: 'bg-[#14b8a6]' },
  { id: 'cadastro', label: 'Cadastrar Paciente', icon: <UserPlus size={20} />, color: 'bg-[#10b981]' },
  { id: 'infectologia', label: 'Infectologia', icon: <ShieldCheck size={20} />, color: 'bg-[#059669]' },
  { id: 'Clínica Médica', label: 'Clínica Médica', icon: <Hospital size={20} />, color: 'bg-[#2563eb]' },
  { id: 'Clínica Cirúrgica', label: 'Clínica Cirúrgica', icon: <Syringe size={20} />, color: 'bg-[#4f46e5]' },
  { id: 'Obstetrícia', label: 'Obstetrícia', icon: <Heart size={20} />, color: 'bg-[#db2777]' },
  { id: 'Pediatria', label: 'Pediatria', icon: <Heart size={20} />, color: 'bg-[#e11d48]' },
  { id: 'Sala Vermelha', label: 'Sala Vermelha', icon: <AlertCircle size={20} />, color: 'bg-[#dc2626]' },
  { id: 'Pronto Socorro', label: 'Pronto Socorro', icon: <Ambulance size={20} />, color: 'bg-[#ea580c]' },
  { id: 'Ambulatório', label: 'Ambulatório', icon: <Stethoscope size={20} />, color: 'bg-[#0d9488]' },
  { id: 'UTI Adulto', label: 'UTI Adulto', icon: <Activity size={20} />, color: 'bg-[#b91c1c]' },
  { id: 'Centro Cirúrgico', label: 'Centro Cirúrgico', icon: <Scissors size={20} />, color: 'bg-[#7c3aed]' },
  { id: 'finalizados', label: 'Painel Finalizados', icon: <CheckSquare size={20} />, color: 'bg-[#475569]' },
  { id: 'relatorios', label: 'Relatórios', icon: <FileText size={20} />, color: 'bg-[#3b82f6]' },
];
